import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";
import ProfileBadge from "@/components/ProfileBadge";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="grid grid-cols-1 md:grid-cols-5 items-start justify-start h-auto md:h-screen w-full max-w-[70rem] mx-auto overflow-hidden">
          <div className="flex flex-col-reverse md:flex-row w-full bg-red-300 col-auto md:col-span-2">
            <NavigationBar />
            <ProfileBadge />
          </div>
          <div className="w-full col-auto md:col-span-3 bg-green-300">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
